url: http://pohutukawacoastmassage.co.nz
baseurl:

# Site settings
title: Pohutukawa Coast Massage
email: contact@pohutukawacoastmassage.co.nz
description: "Relaxation massage situated in the Pohutukawa Coast"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
# people:
# - name: Kay Garland
#   pic: 1
#   position: Lead Designer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/pages/Pohutukawa-Coast-Massage/395170440679294

# Postal address (add as many lines as necessary)
address:
  - line: 897 Whitford-Maraetai Road
  - line: Beachlands, New Zealand

# Build settings
markdown: kramdown
permalink: pretty
